Building DAG of jobs...
Using shell: /bin/bash
Job counts:
	count	jobs
	1	down_sample_bams
	1
Error in rule down_sample_bams:
    jobid: 0
    output: ../data/bam/1240k/downsampled/KM4_allmerged_rmdup_reheader_1240k_0.1x.trimmed.bam

RuleException:
KeyError in line 33 of /project/jnovembre/chichun/ancient-imputation-experiment/snakemake/snakefile_downsample_bams.py:
'{wildcards.id}'
  File "/project/jnovembre/chichun/ancient-imputation-experiment/snakemake/snakefile_downsample_bams.py", line 33, in __rule_down_sample_bams
  File "/home/chichun/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2139, in __getitem__
  File "/home/chichun/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2146, in _getitem_column
  File "/home/chichun/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 1842, in _get_item_cache
  File "/home/chichun/.local/lib/python3.6/site-packages/pandas/core/internals.py", line 3843, in get
  File "/home/chichun/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2527, in get_loc
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "/project/jnovembre/chichun/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /project/jnovembre/chichun/ancient-imputation-experiment/snakemake/.snakemake/log/2018-05-09T232329.486066.snakemake.log
